### ISSUE TITLE
D1_ERROR: near "-": syntax error at offset 30

### ISSUE THREAD

**Issue by hrueger** [JacobLinCool/d1-manager#49]
Hi @JacobLinCool,
first of all, thanks for this cool project. I'm running into an error with one of my databases though. Here's the logs:
```
No deployment specified. Using latest deployment for production environment.
Connected to deployment [redacted], waiting for logs...
  (debug) d1-manager:dbms Database Bindings: +0ms DB_cf-pages-prisma-d1-test, DB_dts-prod-1, DB_prod-logs
  (debug) d1-manager:server-error Error: D1_ERROR: near "-": syntax error at offset 30
    at D1Database._sendOrThrow (cloudflare-internal:d1-api:66:19)
    at async D1PreparedStatement.all (cloudflare-internal:d1-api:181:46)
    at async GET7 (functionsWorker-0.2088450453108457.js:19004:27)
    at async render_endpoint (functionsWorker-0.2088450453108457.js:19457:20)
    at async resolve2 (functionsWorker-0.2088450453108457.js:22691:22)
    at async Object.handle (functionsWorker-0.2088450453108457.js:5071:22)
    at async respond (functionsWorker-0.2088450453108457.js:22585:22)
    at async Object.fetch (functionsWorker-0.2088450453108457.js:23051:13) +0ms
```
any idea what might cause this? Thanks in advance.

**Comment by JacobLinCool** [comment]
I am not sure...

Is there any special character in the table name or column name? I may have forgotten to escape something...

**Comment by hrueger** [comment]
The database is called `prod-logs`, the table `logs-v1`.
Here's the schema:
```js
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const logsTableV1 = sqliteTable("logs-v1", {
    id: integer("id", { mode: "number" }).primaryKey({ autoIncrement: true }),

    // Timestamp
    timestamp: integer("timestamp", { mode: "number" }).notNull(),

    // Request details
    method: text("method").notNull(),
    url: text("url").notNull(),
    statusCode: integer("statusCode").notNull(),
    duration: integer("duration").notNull(),

    // Location details
    ip: text("ip").notNull(),
    country: text("country"),
    regionCode: text("regionCode"),
    city: text("city"),

    // Service details
    microservice: text("microservice").notNull(),
    deployment: text("deployment").notNull(),
    environment: text("environment").notNull(),

    // User details
    customerSessionId: text("customerSessionId"),
    userId: text("userId"),
    superadminId: text("superadminId"),

    // Additional data
    data: text("data"),

    // Error details
    error: text("error"),
});
```

Maybe `timestamp` is a problem?

**Comment by johtso** [comment]
I'm guessing it's the hyphen in the database name

**Comment by johtso** [comment]
https://stackoverflow.com/a/3694305/311220

A table name with a hyphen would need to be quoted.

https://github.com/search?q=repo:JacobLinCool/d1-manager+prepare+table&type=code

**Comment by hrueger** [comment]
I have multiple databases with hyphens in the name and the other ones work fine. So it's probably the hyphen in the table name.

**Comment by moalamri** [comment]
Hi @JacobLinCool 
Thank you for this great tool,
It seems that Cloudflare takes the table name directly from the URL param without adding anything to it.
By simply adding single quotes to the table name in the URL it will solve the issue e.g. `/api/db/demodb/'table-name'/data?...`
I have also tested the case with database names with hyphen and it seems that Cloudflare accept using hyphens in database names, but unlike table names it is processed from Cloudflare side and quoting the database name in URLs isn't necessary.
I have also tested columns and it has the same issue as with table names, I will make a PR with suggested fix for both table and column names.

**Comment by JacobLinCool** [comment]
Hello @moalamri 

Thank you for your observations and contributions on PR #53.

I want to clarify that the /api/... endpoints are not part of the Cloudflare API; they are located [here](https://github.com/JacobLinCool/d1-manager/tree/main/src/routes/api).

Since the database name is not presented in the SQL statement, it seems I forgot to escape the table name in the following places:

https://github.com/JacobLinCool/d1-manager/blob/1e980bdcbae631cd2e413328284c137be5224aff/src/routes/api/db/%5Bdatabase%5D/%5Btable%5D/%2Bserver.ts#L21

https://github.com/JacobLinCool/d1-manager/blob/1e980bdcbae631cd2e413328284c137be5224aff/src/routes/api/db/%5Bdatabase%5D/%5Btable%5D/data/%2Bserver.ts#L30

https://github.com/JacobLinCool/d1-manager/blob/1e980bdcbae631cd2e413328284c137be5224aff/src/routes/api/db/%5Bdatabase%5D/%5Btable%5D/data/%2Bserver.ts#L61

https://github.com/JacobLinCool/d1-manager/blob/1e980bdcbae631cd2e413328284c137be5224aff/src/routes/api/db/%5Bdatabase%5D/%5Btable%5D/data/%2Bserver.ts#L98

https://github.com/JacobLinCool/d1-manager/blob/1e980bdcbae631cd2e413328284c137be5224aff/src/routes/api/db/%5Bdatabase%5D/%5Btable%5D/data/%2Bserver.ts#L122

Maybe your utility functions should be applied to those places instead of replacing them in the URL at the frontend side. (It seems strange to see quotes in an URL)

**Comment by moalamri** [comment]
Hey @JacobLinCool 
My bad :) I looked into the component and really assumed they were calling Cloudflare.
I will work on it soon, maybe simplify it more by always applying escape to identifiers since they can accept a lot of special characters.
